### ISSUE TITLE
bunch of error messages that might help

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint#2]
Uh, this bunch of error messages is caused by me using yayalint like this:
```bat
C:\Users\steve02081504\Desktop\temp\yayalint\yayalint.bat E:\ssp\ghost\Taromati2\ghost\master\shiori\aya.txt
```
I'm not sure if I'm using it right, but I think these are too many errors in report.

**[lint_with_taro.log](https://github.com/Tatakinov/yayalint/files/9033205/lint.with.taro.log)**

Some obvious possible changes you can do:
- No error reporting for `_loading_order_override` or `_loading_order` file not found
- Marking the `load`, `unload`, and `request` functions as root functions
- Allowing user-defined regular matches for root functions ([like this in taro](https://github.com/Taromati2/ghost/blob/fc2a5423ce4cfcdf1a4d2147a4c611c4b8a38208/master/dic/dev/lint.dic#L5L14))

I'm not sure how much this error log tells us(After all, I know almost nothing about lua), but I thought it might give you some help!
If you don't like this, feel free to close the issue

For testing purposes, you might consider clone [Taromati2/ghost](https://github.com/Taromati2/ghost).

**Comment by Tatakinov** [comment]
I think that v1.2.0 has supported it to some extent.

It seems that one of the reasons for the long log is that the reference* is undefined.
I think the reason is that yayalint cannot detect variable definitions by LETTONAME or EVAL.

However, due to my lack of programming skills, it is difficult to detect them.

**Comment by steve02081504** [comment]
I think it's a bit too difficult to detect EVAL
How about adding a regular expression filter just like the function?

**Comment by Tatakinov** [comment]
I was able to implement it maybe in v1.3.1, please try it out.

**Comment by steve02081504** [comment]
Sorry, I've just been to two exams
I added `^reference%d+$` to the list of predefined variables, but it seems that the error log is not reduced as expected
Here is my [configuration file & the output](https://github.com/Tatakinov/yayalint/files/9034588/yayalint.zip)

**Comment by Tatakinov** [comment]
I'm sorry. There was a mistake in the program.
It is probably fixed in v1.3.2.

**Comment by steve02081504** [comment]
Thank you for all your hard work!
I'm wondering if the filtering of functions uses the same logic as variables though, and only the variable part was changed in this revision?

**Comment by Tatakinov** [comment]
Yes, the variable part only.
Are there any problems remaining?

**Comment by steve02081504** [comment]
Yes, I've noticed that some functions are reported as errors even in the predefine or used list, such as `IARRAY` and some others.

**Comment by nikolat** [comment]
[slight modification for yayalint](https://github.com/nikolat/balloonselector/commit/feaedacc3a96ae9386f8b6f48c2ca7816dcd4335)
It must be because it was recognized as a variable, not a function.
I think function calls with no arguments should be written as `IARRAY()`, not `IARRAY`.
That way, syntax highlighting works and is easier for us to understand.

**Comment by steve02081504** [comment]
Oh I just noticed that these hints are talking about variables, sorry for the misstatement
But I think not having to write call signs after functions is a special feature of yaya, and one that can sometimes make code more concise - even if the syntax is sometimes misleading.
Although somewhat cumbersome, I wonder if lint could force any variable that hits the func.predefined rule to be treated as a function, and reorganise the function list after reading the full dic file contents to circumvent any function misclassification as a variable?

**Comment by Tatakinov** [comment]
maybe fixed in v1.3.6.

**Comment by steve02081504** [comment]
```
attempt to index a nil value
stack traceback:
        [C]: in for iterator 'for iterator'
        ...ers\steve02081504\Desktop\temp\yayalint\user_defined.lua:241: in function 'user_defined.isUserDefinedFunction'
        [string "yayalint"]:753: in upvalue 'recursive'
        [string "yayalint"]:543: in upvalue 'recursive'
        [string "yayalint"]:849: in upvalue 'interpret'
        [string "yayalint"]:985: in local 'main'
        [string "yayalint"]:990: in local 'func'
        [string "yayalint"]:41: in main chunk
Press any key to continue . . .
```
This appeared when I was using the latest version of yayalint
Hope this helps

**Comment by Tatakinov** [comment]
That error should not occur, so the configuration may be wrong.
Is func.predefined missing?

Please use v1.3.7 or later, as another bug was found in v1.3.6.

**Comment by steve02081504** [comment]
Oh sorry I got it wrong again
BTW, There are two small problems here:
```
syntax error:   ../dic\games\Gobang\Gobang.dic  before  line    970     col     9       data            elseif fight-defense>-8
syntax error:   ../dic\games\linkwnd.dic        before  line    2270    col     62      data            for _buff = FREAD(_mapfile);_buff != -1&& _buff !='';;_buff = FREAD(_mapfile){
```

**Comment by Tatakinov** [comment]
```
syntax error:   ../dic\games\linkwnd.dic        before  line    2270    col     62      data            for _buff = FREAD(_mapfile);_buff != -1&& _buff !='';;_buff = FREAD(_mapfile){
```
This is fixed in v1.3.9.
However, Gobang.dic line 969
```
        k1=0.5f
              ^
```
It's odd to have `f` (is variable?) right after a number.

**Comment by steve02081504** [comment]
Thanks for the info, I fixed it!
I think it was a minor error on the part of whoever wrote the function, although I'm not sure why such code wouldn't cause yaya to report error.😂

**Comment by steve02081504** [comment]
I still have some suggestions for information purposes:
- Provide a function to ignore unused functions and global variables in a specific dic or dicdir
  You know, sometimes I just reference some library without using the full functionality of the library
- Warn about similar variable names
  Sometimes I spell `username` as `usermane` or `uername`, but I don't think lint will warn if I assign a value to a misspelled variable
- lint configuration files placed in the ghost directory
  When I use lint for different ghosts or when I am working on a ghost with others, it is useful to have lint configuration files that can be distinguished by the ghost directory and shared via git.

**Comment by steve02081504** [comment]
```
[string "yayalint"]:747: attempt to concatenate a nil value (field 'col')
stack traceback:
        [string "yayalint"]:747: in upvalue 'recursive'
        [string "yayalint"]:854: in upvalue 'interpret'
        [string "yayalint"]:991: in local 'main'
        [string "yayalint"]:996: in local 'func'
        [string "yayalint"]:41: in main chunk
Press any key to continue . . .
```
Sorry, I've been on my way home for the past 2 days so I haven't had time to touch the computer
After I updated yayalint to the latest version, I got this error
This time I checked carefully and there should be no config error

**Comment by Tatakinov** [comment]
Sorry, it's my mistake.
fixed in v1.5.2.

**Comment by steve02081504** [comment]
```ayaya
_l="%(_lunar[0])年%(_lunar[1])月%(_lunar[2])日　%(_lunar[7])\n%(_lunar[4])(%(_lunar[3]))年 %(_lunar[5])月%(_lunar[6])\n%(_jieqi)%(_lunar[12])(%(_lunar[13])月%(_lunar[14])日)\n%(_lunar[9])\n%(_lunar[10])"
if _i+1==_d
	_w+="\_l[%(_x-5),%(_y)][\q[%(_i+1),OnCalendar,%(_l),%(_year),%(_m),%(_i+1),##]]"
elseif _i+1==day && _m==month && _year==year
	_w+="\_l[%(_x),%(_y)]\f[color,110,110,110]\f[underline,1]\q[%(_i+1),OnCalendar,%(_l),%(_year),%(_m),%(_i+1),##]\f[default]\f[sup,1]◀\f[default]"
elseif _lunar[17]==0 || _lunar[17]==6
	_w+="\f[color,255,0,0]\_l[%(_x),%(_y)]\q[%(_i+1),OnCalendar,%(_l),%(_year),%(_m),%(_i+1),##]\f[color,default]"
elseif _lunar[9] || _lunar[10]
	_w+="\f[color,110,110,110]\_l[%(_x),%(_y)]\q[%(_i+1),OnCalendar,%(_l),%(_year),%(_m),%(_i+1),##]\f[default]"
else
	_w+="\_l[%(_x),%(_y)]\q[%(_i+1),OnCalendar,%(_l),%(_year),%(_m),%(_i+1),##]"
```
I have this code where `_l` is only used in the `%()` formatting character in the string
But it looks like lint doesn't detect this use and marks `_l` as an unused variable
Could you please provide a fix for this problem?

**Comment by Tatakinov** [comment]
maybe fixed in v1.5.3.

**Comment by steve02081504** [comment]
Thanks for your efforts!
Basically there are ok now, if I find any new ones later I will open another issue
